[[icedos.repositories]]
url = "github:icedos/apps"
modules = [
  "bash",
  "btop",
  "celluloid",
  "codium",
  "direnv",
  "faugus-launcher",
  "flatpak",
  "gamemode",
  "gamescope",
  "git",
  "input-remapper",
  "kitty",
  "lact",
  "lsfg-vk",
  "mangohud",
  "nautilus",
  "ncdu",
  "nh",
  "nix",
  "nix-health",
  "nixfmt",
  "obs",
  "proton-launch",
  "sd-inhibitor",
  "ssh",
  "steam",
  "sunshine",
  "toolset",
  "zed",
  "zen",
  "zsh",
]

[[icedos.repositories]]
url = "github:icedos/desktop"
modules = ["adwaita-qt", "clear-xdg-portals", "displays", "gdm"]

[[icedos.repositories]]
url = "github:icedos/hardware"
modules = [
  "bluetooth",
  "disable-ipv6",
  "graphics",
  "kernel",
  "monitors",
  "mounts",
  "pipewire",
  "radeon",
  "systemd-boot",
  "uinput",
  "upower",
  "xpadneo",
  "zram",
]

[[icedos.repositories]]
url = "github:icedos/gnome"

[[icedos.repositories]]
url = "github:icedos/tweaks"
modules = ["gaming", "kernel"]

[[icedos.repositories]]
url = "github:icedos/users"

[[icedos.repositories]]
url = "github:icedos/providers"
modules = ["chaotic"]

[icedos.applications]
defaultBrowser = "zen.desktop"
defaultEditor = "dev.zed.Zed.desktop"
extraPackages = [
# "cemu", # Wiuu
  # "duckstation", # PS1
  # "heroic", # Cross-platform Epic Games Launcher
  # "pcsx2", # PS2
  # "ppsspp", # PSP
  # "prismlauncher", # Minecraft launcher
  # "rpcs3", # PS3
  
  "appimage-run",
  "audacity", # Sound editor with graphical UI
  "blanket",
  "bottles", # Wine manager
  "curtail", # Image compressor
  "discord",
  "eartag", # Simple music tag editor
  "fragments",
  "gimp3", # GNU Image Manipulation Program
  "gsound", # Small library for playing system sounds (required to show file properties in Nautilus)
  "handbrake", # Tool for converting video files and ripping DVDs
  "jetbrains.webstorm", # Professional IDE for Web and JavaScript development
  "mission-center", # CPU, Memory, Disk, Network and GPU usage monitor
  "mousai", # Song recognizer
  "nicotine-plus", # p2p music sharing platform
  "parabolic", # Download web video and audio
  "signal-desktop",
  "spek", # Audio file spectrogram analysis
  "spotify",
  "sticky-notes", # Simple sticky notes app
  "whatsapp-electron",
  "warp", # File sync
]
insecurePackages = []

[icedos.applications.git.users.jim]
username = "TheTackledPeanut"
email = "dimgavridis@gmail.com"

[icedos.applications.mangohud]
fpsLimit = "144,60,0"

[icedos.applications.sd-inhibitor.users.jim.watchers.pipewire]
inputsToIgnore = ["Noise Canceling source", "Peak detect", "cava"]
outputsToIgnore = ["Discord", "Element"]

[icedos.applications.steam]
beta = true
downloadsWorkaround = true

[[icedos.applications.zen.profiles]]
default = true
exec = "default"
privacy = false

[icedos.desktop.gnome]
titlebarLayout = "appmenu:minimize,maximize,close"

[icedos.desktop.gnome.extensions]
arcmenu = true
dashToPanel = true

[icedos.desktop.gnome.users.jim]
startupScript = "steam & signal-desktop"

[icedos.desktop.gnome.users.jim.pinnedApps.arcmenu]
enable = true
list = ["spotify.desktop"]

[icedos.desktop.gnome.users.stef.pinnedApps.shell]
enable = true
list = [
  "steam.desktop",
  "discord.desktop",
  "signal.desktop",
  "zen.desktop",
]

[icedos.desktop]
autologinUser = "jim"

[icedos.desktop.users.jim]

[icedos.hardware.bootloaders.systemd-boot]
mountPoint = "/boot"

[icedos.hardware.kernel]
version = "cachyos"

[[icedos.hardware.mounts]]
path = "/"
device = "/dev/disk/by-uuid/e2a8d4bf-b1fc-446f-b347-c3671eda1ccb"
fsType = "btrfs"
flags = ["compress=zstd", "nofail", "x-gvfs-show"]


[[icedos.hardware.monitors]]
name = "DP-2"
resolution = "1920x1080"
refreshRate = 165
position = "0x0"
rotation = 0

[[icedos.hardware.monitors]]
name = "DP-1"
resolution = "1920x1080"
refreshRate = 60
position = "1920x0"
rotation = 0

[icedos.system]
version = "25.05"

[icedos.users.jim]
description = "Jim"
